name: nimbus_weather
description: "A complete modern Flutter weather application with dynamic gradients, animated icons, and comprehensive forecasting."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management (Riverpod)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Networking
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Geolocation
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  
  # UI/UX Enhancements
  lottie: ^3.1.3
  shared_preferences: ^2.2.3
  go_router: ^14.0.0
  intl: ^0.19.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Build Runner & Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.5
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - .env